// packages/react/src/Tessera.tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import { EditorContent, useEditor } from '@tiptap/react'
import type { Editor } from '@tiptap/react'
import type { Content } from '@tiptap/core'
import { DragHandle } from '@tiptap/extension-drag-handle-react'
import {
  createTesseraExtensions,
  createTesseraT,
} from '@tessera-editor/core'
import type {
  TesseraLocale,
  UploadService,
  StorageService,
  CommentStore,
  IdentityService,
} from '@tessera-editor/core'
import { createAiController, aiSlashItems } from '@tessera-editor/ai'
import type { AIRuntime, SuggestionSession } from '@tessera-editor/ai'
import { ImageBlockView } from './ImageNodeView'
import { AiTableCellViewExtension, AiTableHeaderViewExtension } from './TableNodeViews'
import { EmbedBlockView, TocBlockView } from './EmbedTocViews'
import { createSlashRenderer } from './SlashMenu'
import { EmptyLineToolbar } from './EmptyLineToolbar'
import { SelectionToolbar } from './SelectionToolbar'
import { FindReplacePanel, AskPanel, SuggestionBar } from './Panels'
import { HistoryPanel } from './HistoryPanel'
import { CommentPanel } from './CommentPanel'
import { BlockContextMenuUI } from './BlockMenu'
import { TesseraContext } from './context'
import '@tessera-editor/core/styles.css'

export interface TesseraProps {
  /** Initial document (JSON / HTML / markdown string). Host owns persistence. */
  content?: Content
  locale?: TesseraLocale
  /** Injected image upload capability (ADR-0001 family). */
  upload?: UploadService
  /** v1.1: version-history snapshot storage. */
  storage?: StorageService
  /** v1.1: inline comment persistence. */
  comments?: CommentStore
  /** v1.1: current user (comment authorship). */
  identity?: IdentityService
  /** Injected model runtime; presence enables all AI surfaces. */
  ai?: AIRuntime
  /** v1.1: idle window for history auto-capture (playground uses short ones) */
  historyIdleMs?: number
  onUpdate?: (editor: Editor) => void
  onCreate?: (editor: Editor) => void
}

/**
 * Batteries-included editor (M1+M2 scope). Slite-style: empty-line toolbar,
 * slash menu, selection toolbar, drag handle — deliberately NOT Notion's
 * floating "+".
 */
export function Tessera({
  content,
  locale = 'zh-CN',
  upload,
  storage,
  comments,
  identity,
  ai: runtime,
  historyIdleMs,
  onUpdate,
  onCreate,
}: TesseraProps) {
  const t = useMemo(() => createTesseraT(locale), [locale])
  const [session, setSession] = useState<SuggestionSession | null>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)

  const extensions = useMemo(
    () =>
      createTesseraExtensions({ locale, historyIdleMs }).map(ext => {
        if (ext.name === 'tesseraSlashMenu') {
          return ext.configure({
            render: createSlashRenderer(t),
            extraItems: runtime
              ? (ctx: Parameters<NonNullable<import('@tessera-editor/core').SlashMenuOptions['extraItems']>>[0]) =>
                  aiSlashItems({ editor: ctx.editor, runtime, t: ctx.t })
              : undefined,
          })
        }
        if (ext.name === 'imageBlock') {
          return ImageBlockView
        }
        if (ext.name === 'tableCell') {
          return AiTableCellViewExtension
        }
        if (ext.name === 'tableHeader') {
          return AiTableHeaderViewExtension
        }
        if (ext.name === 'embedBlock') {
          return EmbedBlockView
        }
        if (ext.name === 'tocBlock') {
          return TocBlockView
        }
        return ext
      }),
    [locale, t, runtime, historyIdleMs],
  )

  const editor = useEditor({
    extensions,
    content,
    onUpdate: ({ editor: e }) => onUpdate?.(e),
    onCreate: ({ editor: e }) => onCreate?.(e),
    editorProps: {
      attributes: {
        class: 'tessera-doc',
        spellcheck: 'false',
      },
      handlePaste: (_view, event) => {
        const file = Array.from(event.clipboardData?.files ?? []).find(f => f.type.startsWith('image/'))
        if (file) {
          void uploadAndInsert(file)
          return true
        }
        return false
      },
      handleDrop: (_view, event, _slice, moved) => {
        if (moved) {
          return false
        }
        const file = Array.from(event.dataTransfer?.files ?? []).find(f => f.type.startsWith('image/'))
        if (file) {
          event.preventDefault()
          void uploadAndInsert(file)
          return true
        }
        return false
      },
    },
  })

  async function uploadAndInsert(file: File) {
    if (!editor) {
      return
    }
    const storage = editor.storage as unknown as Record<string, { upload?: UploadService }>
    const svc = storage.tesseraServices?.upload
    if (!svc) {
      return
    }
    try {
      const asset = await svc.uploadImage(file)
      editor.chain().focus().setImage({ src: asset.url, alt: asset.name }).run()
    } catch (err) {
      console.error('[Tessera] image upload failed:', err)
    }
  }

  // injected services stay current
  useEffect(() => {
    if (editor) {
      const bag = (editor.storage as unknown as Record<string, Record<string, unknown>>).tesseraServices ?? {}
      ;(editor.storage as unknown as Record<string, Record<string, unknown>>).tesseraServices = {
        ...bag,
        upload,
        storage,
        comments,
        identity,
      }
    }
  }, [editor, upload, storage, comments, identity])

  // editor events → UI (image picker, sessions from slash AI items)
  useEffect(() => {
    if (!editor) {
      return
    }
    const pickImage = () => fileInputRef.current?.click()
    const onSession = (payload: { session: SuggestionSession | null }) => setSession(payload.session)
    editor.on('tessera:insertImage', pickImage)
    editor.on('tessera:session', onSession as never)
    return () => {
      editor.off('tessera:insertImage', pickImage)
      editor.off('tessera:session', onSession as never)
    }
  }, [editor])

  const ai = useMemo(
    () => (editor && runtime ? createAiController(editor, runtime, locale) : null),
    [editor, runtime, locale],
  )

  if (!editor) {
    return null
  }

  return (
    <TesseraContext.Provider value={{ editor, locale, t, ai }}>
      <div className="tessera-root">
        <EditorContent editor={editor} />
        {/* 'left' (vertical center) instead of the default 'left-start': the
            handle must sit mid-row like Slite, not above multi-line blocks */}
        <DragHandle
          editor={editor}
          pluginKey="tesseraDragHandle"
          computePositionConfig={{ placement: 'left', strategy: 'absolute' }}
        >
          <div className="tessera-drag-handle">⠿</div>
        </DragHandle>
        <EmptyLineToolbar />
        <SelectionToolbar onSession={setSession} />
        <FindReplacePanel />
        <AskPanel />
        <HistoryPanel />
        <CommentPanel />
        <BlockContextMenuUI />
        <SuggestionBar session={session} onClear={() => setSession(null)} />
        <input
          ref={fileInputRef}
          type="file"
          accept="image/*"
          hidden
          onChange={e => {
            const file = e.target.files?.[0]
            if (file) {
              void uploadAndInsert(file)
            }
            e.target.value = ''
          }}
        />
      </div>
    </TesseraContext.Provider>
  )
}

// packages/vue/src/Tessera.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, shallowRef, watch } from 'vue'
import { Editor, EditorContent } from '@tiptap/vue-3'
import { DragHandle } from '@tiptap/extension-drag-handle'
import { createEmojiRenderer } from './emojiRenderer'
import {
  createTesseraExtensions,
  createTesseraT,
} from '@tessera-editor/core'
import type {
  TesseraLocale,
  UploadService,
  StorageService,
  CommentStore,
  IdentityService,
} from '@tessera-editor/core'
import { createAiController, aiSlashItems } from '@tessera-editor/ai'
import type { AIRuntime, SuggestionSession } from '@tessera-editor/ai'
import { createSlashRenderer } from './slashRenderer'
import {
  ImageBlockView,
  AiTableCellViewExtension,
  AiTableHeaderViewExtension,
  EmbedBlockView,
  TocBlockView,
} from './views/extensions'
import EmptyLineToolbar from './EmptyLineToolbar.vue'
import SelectionToolbar from './SelectionToolbar.vue'
import FindReplacePanel from './FindReplacePanel.vue'
import AskPanel from './AskPanel.vue'
import HistoryPanel from './HistoryPanel.vue'
import CommentPanel from './CommentPanel.vue'
import BlockMenu from './BlockMenu.vue'
import SuggestionBar from './SuggestionBar.vue'
import { provideTessera } from './context'
import '@tessera-editor/core/styles.css'

const props = withDefaults(
  defineProps<{
    content?: unknown
    locale?: TesseraLocale
    upload?: UploadService
    storage?: StorageService
    comments?: CommentStore
    identity?: IdentityService
    ai?: AIRuntime
    historyIdleMs?: number
  /** v1.1: document column max-width in px. */
  docWidth?: number
  }>(),
  { locale: 'zh-CN' },
)

const emit = defineEmits<{
  (e: 'update', editor: import('@tiptap/core').Editor): void
  (e: 'create', editor: import('@tiptap/core').Editor): void
}>()

const t = computed(() => createTesseraT(props.locale))

const docWidthStyle = computed(() =>
  props.docWidth ? ({ '--te-doc-max-width': `${props.docWidth}px` }) : undefined,
)
const editor = shallowRef<Editor | null>(null)
const session = ref<SuggestionSession | null>(null)
const fileInput = ref<HTMLInputElement | null>(null)

function buildExtensions() {
  return createTesseraExtensions({ locale: props.locale, historyIdleMs: props.historyIdleMs }).map(ext => {
    if (ext.name === 'tesseraSlashMenu') {
      return ext.configure({
        render: createSlashRenderer(t.value),
        extraItems: props.ai
          ? (ctx: { editor: Editor; t: ReturnType<typeof createTesseraT> }) =>
              aiSlashItems({ editor: ctx.editor, runtime: props.ai!, t: ctx.t })
          : undefined,
      })
    }
    if (ext.name === 'imageBlock') {
      return ImageBlockView
    }
    if (ext.name === 'tableCell') {
      return AiTableCellViewExtension
    }
    if (ext.name === 'tableHeader') {
      return AiTableHeaderViewExtension
    }
    if (ext.name === 'embedBlock') {
      return EmbedBlockView
    }
    if (ext.name === 'tocBlock') {
      return TocBlockView
    }
    return ext
  })
}

async function uploadAndInsert(file: File) {
  const ed = editor.value
  if (!ed) return
  const bag = (ed.storage as unknown as Record<string, { upload?: UploadService }>).tesseraServices
  if (!bag?.upload) return
  try {
    const asset = await bag.upload.uploadImage(file)
    ed.chain().focus().setImage({ src: asset.url, alt: asset.name }).run()
  } catch (err) {
    console.error('[Tessera] image upload failed:', err)
  }
}

onMounted(() => {
  const ed = new Editor({
    extensions: [
      ...buildExtensions().map(ext =>
        ext.name === 'tesseraEmojiMenu'
          ? (ext as unknown as { configure: (o: { render: unknown }) => typeof ext }).configure({
              render: createEmojiRenderer(),
            })
          : ext,
      ),
      // 'left' (vertical center) instead of the default 'left-start': the
      // handle must sit mid-row like Slite, not above multi-line blocks.
      // nested: hovering a list item targets that item (Slite-style).
      DragHandle.configure({
        computePositionConfig: { placement: 'left', strategy: 'absolute' },
      }),
    ],
    content: props.content as never,
    onUpdate: ({ editor: e }) => emit('update', e),
    onCreate: ({ editor: e }) => emit('create', e),
    editorProps: {
      attributes: { class: 'tessera-doc', spellcheck: 'false' },
      handlePaste: (_view, event) => {
        const file = Array.from(event.clipboardData?.files ?? []).find(f => f.type.startsWith('image/'))
        if (file) {
          void uploadAndInsert(file)
          return true
        }
        return false
      },
      handleDrop: (_view, event, _slice, moved) => {
        if (moved) return false
        const file = Array.from(event.dataTransfer?.files ?? []).find(f => f.type.startsWith('image/'))
        if (file) {
          event.preventDefault()
          void uploadAndInsert(file)
          return true
        }
        return false
      },
    },
  })
  editor.value = ed
  syncServices()

  ed.on('tessera:insertImage', () => fileInput.value?.click())
  ed.on('tessera:session', ((payload: { session: SuggestionSession | null }) => {
    session.value = payload.session
  }) as never)
})

function syncServices() {
  const ed = editor.value
  if (!ed) return
  ;(ed.storage as unknown as Record<string, Record<string, unknown>>).tesseraServices = {
    ...((ed.storage as unknown as Record<string, Record<string, unknown>>).tesseraServices ?? {}),
    upload: props.upload,
    storage: props.storage,
    comments: props.comments,
    identity: props.identity,
  }
}

watch(() => [props.upload, props.storage, props.comments, props.identity], syncServices)

onBeforeUnmount(() => {
  editor.value?.destroy()
  editor.value = null
})

const aiController = computed(() => {
  const ed = editor.value
  return ed && props.ai ? createAiController(ed, props.ai, props.locale) : null
})

provideTessera({
  get editor() {
    return editor.value!
  },
  get locale() {
    return props.locale
  },
  get t() {
    return t.value
  },
  get ai() {
    return aiController.value
  },
} as never)
</script>

<template>
  <div v-if="editor" class="tessera-root">
    <EditorContent :editor="editor" />
    <EmptyLineToolbar />
    <SelectionToolbar @session="s => (session = s)" />
    <FindReplacePanel />
    <AskPanel />
    <HistoryPanel />
    <CommentPanel />
    <BlockMenu />
    <SuggestionBar :session="session" @clear="session = null" />
    <input
      ref="fileInput"
      type="file"
      accept="image/*"
      hidden
      @change="event => {
        const file = (event.target as HTMLInputElement).files?.[0]
        if (file) uploadAndInsert(file)
        ;(event.target as HTMLInputElement).value = ''
      }"
    />
  </div>
</template>
